name: Container security scan

on:
  schedule:
    - cron: "0 4 * * *"
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  container-security-scan:
    runs-on: ubuntu-latest
    container: ghcr.io/aquasecurity/trivy:latest
    outputs:
      noOfVulns: ${{ steps.vuln-scan.outputs.noOfVulns }}
      baseImageVulns: ${{ steps.vuln-scan.outputs.baseImageVulns }}
    steps:
      - name: Run Trivy vulnerability scanner
        id: vuln-scan
        run: |
          noOfVulns=$(trivy -q image --severity UNKNOWN,MEDIUM,HIGH,CRITICAL -o trivy-scan-result.txt ghcr.io/breucode/imisu:stable | grep "Total: " | awk '{print $2}')
          baseImageVulns=$(trivy -q image --severity UNKNOWN,MEDIUM,HIGH,CRITICAL gcr.io/distroless/base-debian11 | grep "Total: " | awk '{print $2}')
          echo "::set-output name=noOfVulns::$noOfVulns"
          echo "::set-output name=baseImageVulns::$baseImageVulns"
      - name: Upload trivy-scan-result
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-result
          path: trivy-scan-result.txt

  push-badge-and-report:
    runs-on: ubuntu-latest
    needs: container-security-scan
    steps:
      - uses: actions/checkout@v4
        with:
          ref: badges
      - uses: actions/download-artifact@v4
        with:
          name: trivy-scan-result
      - name: Download and commit badge and scan report
        env:
          NO_OF_VULNS: ${{ needs.container-security-scan.outputs.noOfVulns }}
          TRIVY_SCAN_RESULT: ${{ needs.container-security-scan.outputs.trivyScanResult }}
        run: |
          curl "https://img.shields.io/badge/container%20vulns-${NO_OF_VULNS}-informational?style=flat-square&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAMAAAD04JH5AAABI1BMVEUAAAAAAAD///////////////////////////////////////////////////////////8HJC0HJC0HJC0HJC0HJC0HJC0HJC0HJC0HJC0HJC0HJC0HJC0HJC0HJC0HJC3////7ypD++PH95Mj3oT32lCH3my/816z+8uP4r1n6w4L5vHT70J74qEv83rr5tWb969WE2Oqz2ODS5+wIsdUnu9qy5/JKobQNgZvD4OZGxeDg9frw9/losMF00+fw+vyVyNMciaEXttiT3e0rkajB7PXh7/NZqLpVyeKGwM2k0Nqi4u82wN1lzuXR8Pc6ma53uMf7983587T475v9++b+/fL264Hy40/w3zb052j8+dn16XX37Y769cDx4UP48afz5VwfGcjiAAAAAXRSTlMAQObYZgAACVJJREFUeNrtm2l/okgQxvfHNxER8UAR8ABb8WwVz9mJySSbzOz3/xRb7dkHjYAmebP9aoyZqT9V9TxVPTF//fX/ue8oyjeHV9XvRFDUfKVe+zYEZW+VtUJBK1t75Vuyb1TNwuGYOePLkwDFL9YLl1MqfnEdSPH1AnX0Sl5VvvDxrZxW4A60whclAYpfLBUijln9ilaA4tfqeiHy6F8gyZP0ZEerfK4kIfs5sxB7PlOSRHqlws1TKn4SgiA92fkcSYL04oovSPLBrUD5brLzWEnGSU96HihJRbWiiq9rZqleIadeMjX901ohUnpavVzNW4Z6PoaVL5brfI9oD5BkhO/qZrlonaNWySmeWKxixXywJEF6XPG1ShGCGflqpWTq57d03SxVqnnyRpHNw8GdH+i7Zs4iQSpmVEuS1ABDnv072SUpSo+EN2qVGD0CQx5KwSJkc+eD9Hh3IRm+JUetUlN5z8ywMIkrTz0P4Ut6IisGhKJ5jyTFlUerGinMiCSL8440C1OE9Erw+MlHAal7UTW4Z0jszhG+W7HUfCmdE+tlgytDwoUpYuXRc4Za1QppT91SayZPdUuSUb6rVSH9eiH9gboJeYuXZOTKQ+JXCpmOWVPzprgwyesAAMK+r1dVqy6vtK7B0WMIakJCczEAqCvIP6cadYnp1cswhcjJ13KVaIcw82pR4w0BYykAXnuINcCyJP9muXYYgIZhWQb5k5HPRTGULDVHfblUU5Hds6UATrPZdxA1AuqGUY66gIAtqRZ5btPUyF5yGNCRPg3/QoVyAuTsJsM4ANddNfBlmkAGc3rU3i1ORK1eJaNCdIuyapUu9ogH207nBoDrzpfo2ArQgDUt4uahWpHXE5NMK7GLi2pRPxYf2bNhJwGAOyKtAA9TOcPTKQVTlt6OCFxNkL6llon4kNebdDqJAEgdNtAKllqJMNhanCkDn6BaeA7oGbzYdjqJAVzXH3f3Cl8AYko57eYU4rC1mrLHYbvTSQUAdUD8WIL41k1TJM5R4UcQ2g07aQHcNdoQSZYSmiJNQH3bQXoe6nXSAzSCxkGS55yTfzjRTAbQ8wg4Sq+9Q4v0ACMPraEVlhd3LstMWVyIagflXaU3Q176EjQ3Xf8sSdL4JUNNPBRLB/0Q6YHxQcgtdiapAfzu6VWzTyQJLl5NvhQQ+8sZ+7P0hh5upwaYI290kSRWDTWfYinSa/AX0EV6QxvNUgP00ZKisZGST35Dhx1eCbzete4LtEsNMAgalCSaUyUQRw1cknPVnHBRK5H9l056h5FBQoAw6FMAK9wdY8ROgcNFUd2r5LqmM5dyMD6MtxRADw1SA4w5ALzyQ3phgg1Xffrx5/35/e+3/XUDP0vPxjMGIEwNsCQ2QGkCN93RvIXO7gy2rP79+vsXOS/vb/uT9YDvHqU3YMxv9gCAafMgydPCpBXVt+djeHJePw4E5PJz2DkIwO7BAKf3TgtTTn17/UWdlw+4u8C1A7J/jPJoANIDZ0nCwgTl/+cXc16f1DzZOc7Sux9AbMLroPYC5ecv7vwB5S2unc8CZGlCToabKwC8Wu7feYD3vU0rnwdIL8MGY0SjFprTozoKgB65nAqyGBFjxdASTEIagVCCn8wjD0Pa/dl8pB9Gx5BjZlv64AE+mEeeOOz8yzCMLsI7h2xRPD5+e2Hjv7wx3sttAFnG8WkhiZIBaYn9MwvwvLeHjO7ol5kWEmi7tSt92Ucfv+n4vz+YFoD5u2BwMqxknAzgJd2UK4dNwfvemzB7JyeCQSfLWs50IYwjn0nB27/X+P88MQFJzrdSnKQAUHWfqQEjxOYy+Lj04esbGtAdAI8c0i3gMA2aFICrOmRkSr/tO/uPUw6e31BIF4B/ZLYjEwNwVYeyIzoF7tzZ/yAT8eXnExcfItJdDza06GQBmHdp5ZGye+z7XvD089/nH7B9s/HBBhdSU0oBADVgHnk1ZV+7K7hBP6mXFeCaAKYFYRJ5w0wAbj+wR2wKNj7zDaN1K0C7CRd/YrNXwZC1iBQAPu7SI9Bt2sGSITqM6S0XHyTg0V9rY+5bkgPAUjJmXs83XBHgviAAzDDusaY46GQFmLPmQ4qA5zcAth7rCWACs8wAoyVrx+5oHDh+LMAkRPaELQhjAukAxBSsWoHnxwBMBshhNCcmIBUApGDMtp3vMAQcAInPxlswppwawJ1zQiAGSBOwANuQjw8S4BOQDgCE0GoKBNN5JEDb5uODBwyG9wHwE4BUwQtwfyQADHsO8tpsrB5yBJtICSAqj1wLEBqvOIDtAKOQi9Z2OBPMAgB9yBfBbTZw4KybFMBk58CtmNdbKHZgegDoe9QYCc3pIWTPRwQAsj7pwcuwLXqy0+7cD+Cuu9218MVmYxN0l/NmC7e3OwhP/4+QxJMzA4waaDOPyMwYB11vimwHwgsj8dAAi+FDAMj+N/WjijPeIEVB2O6J4Ttbm9+TsgO4Ky9orSLf6G/QoB31nDATvG3nUQDEgJfR5WmJThc5E+4EIJtAJIEEQJwJ9wIQAnuVFCA2fkYAIAgiCCIBxJmUFAD7bgwBjMF5EgBxJvE7k/yH15t+TA5gCG3WtwFmnjCTmPKAayryn98jbz2SEqxshBvNeIDhDiN7K48/s1HspygUBfxVStAcd9HS5y4vDMB2gNBgIs/+At/8EIei4MZKRjDqb2AM0jla0tfQIaTf6Q2l2YeRmeRjLErgyFth3kJMEmgAshLY0vIPSfaTfo4HteayViC7ANWrV4AJbET8NZUpDk7xaSpohVAqybkN42/dZAHI84nXVDr7QboPc4Ekpa1A/tMetY4IR4DhLMSXn45HZd9DGT7OFkylklzBOoK8/uoIMOnZGDkLqfjaIc70sUZoBVsqyQOC0/CXaEcWopjwkwXO/KnKWEmu+lMUYKxgshBJww97WbKfUJLN9RIHCg57cudph+jOz7XGu/PIb0Vt/mmML5Ekl/IpuUS9TGPnYa0gB7g1dlJLMroVQglAOuNLKMlRYoCkYydlK4z9ZADDh2afrkPEwhQB0H5w9hkEQZICAGT/E3/TRnRnDiDF0H+QJFmAT8y+zJ1pgO3C+ZLf9mIWpivA8GHGl2phugDcP3aytcIJ4DFjJ8vCNCbTkOyjX/9bn0dJNgDgk4wvUR3GY7QY4O/7zV8lQLCSfefvPivKN//q9f/n/vMfixZ9xpCfLc8AAAAASUVORK5CYII=" > container-vulns.svg
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.svg
          git add *.txt
          git commit --amend -m "Generate container vulnerability scan"
          git push --force

  base-image-outdated:
    runs-on: ubuntu-latest
    needs: container-security-scan
    if: ${{ needs.container-security-scan.outputs.noOfVulns != needs.container-security-scan.outputs.baseImageVulns }}
    steps:
      - uses: actions/checkout@v4
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/base-image-outdated-template.md
          update_existing: true
