name: Generate native image

on:
  workflow_dispatch:

jobs:
  generate-native-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: "22.2.0"
          java: "java17"
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Generate native image
        run: ./gradlew nativeImage --console=plain
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        if: ${{ success() }}
        with:
          name: native-image
          path: build/native-image/imisu
