name: Generate native image

on:
  workflow_dispatch:

jobs:
  generate-native-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: asdf-vm/actions/install@v1
        env:
          NODEJS_CHECK_SIGNATURES: no
      - name: Generate native image
        run: |
          unset JAVA_HOME
          ./gradlew nativeImage --console=plain
      - name: Upload test reports
        uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: native-image
          path: build/libs/imisu
