on:
  push:
    tags:
      - "**"

name: Create draft release and upload release artifacts

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: asdf-vm/actions/install@v1
        env:
          NODEJS_CHECK_SIGNATURES: no
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Check
        run: |
          unset JAVA_HOME
          ./gradlew check --console=plain
      - name: Build native image
        run: ./gradlew nativeImage --console=plain
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push docker image
        env:
          IMAGE_TAG: ${{ steps.get_version.outputs.version }}
        run: |
          docker build --pull -t ghcr.io/breucode/imisu:"$IMAGE_TAG" -t ghcr.io/breucode/imisu:stable -t ghcr.io/breucode/imisu:latest .
          docker push ghcr.io/breucode/imisu
      - name: Run application
        env:
          IMAGE_TAG: ${{ steps.get_version.outputs.version }}
        run: |
          docker run -p 8080:8080 -v "$(pwd)/imisu.conf:/imisu.conf:ro" "ghcr.io/breucode/imisu:$IMAGE_TAG" &
          sleep 10
      - name: Download swagger
        run: |
          mkdir public
          curl localhost:8080/swagger.json -o public/swagger.json
          curl localhost:8080/swagger-ui/index.html -o public/swagger-ui.html
          curl localhost:8080/swagger-ui/swagger-ui.css -o public/swagger-ui.css
          curl localhost:8080/swagger-ui/favicon-32x32.png -o public/favicon-32x32.png
          curl localhost:8080/swagger-ui/favicon-16x16.png -o public/favicon-16x16.png
          curl localhost:8080/swagger-ui/swagger-ui-bundle.js -o public/swagger-ui-bundle.js
          curl localhost:8080/swagger-ui/swagger-ui-standalone-preset.js -o public/swagger-ui-standalone-preset.js
      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
