on:
  push:
    tags:
      - '**'

name: Create draft release and upload release artifacts

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Check
        run: ./gradlew check
      - name: Release Docker image
        env:
          CR_USER: ${{ secrets.CR_USER }}
          CR_PAT: ${{ secrets.CR_PAT }}
        run: ./gradlew -Djib.to.auth.username="$CR_USER" -Djib.to.auth.password="$CR_PAT" jib
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false