on:
  push:
    tags:
      - "**"

name: Create draft release and upload release artifacts

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: "22.2.0"
          java: "java17"
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Check
        run: ./gradlew check --console=plain
      - name: Inject version
        run: |
          sed -i "s/%ARTIFACT_VERSION%/$VERSION/g" build.gradle.kts
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
      - name: Build native image
        run: ./gradlew nativeImage --console=plain

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: breucode/imisu
          tags: stable latest ${{ steps.get_version.outputs.version }}
          dockerfiles: ./Dockerfile

      - name: Push To ghcr.io
        id: push-to-ghcr-io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Run application
        env:
          IMAGE_TAG: ${{ steps.get_version.outputs.version }}
        run: |
          docker run -p 8080:8080 -v "$(pwd)/imisu.conf:/imisu.conf:ro" "ghcr.io/breucode/imisu:$IMAGE_TAG" &
          sleep 10
      - name: Download swagger
        run: |
          mkdir -p public/swagger-ui
          curl localhost:8080/swagger.json -o public/swagger.json
          curl localhost:8080/swagger-ui/index.html -o public/swagger-ui/index.html
          curl localhost:8080/swagger-ui/swagger-ui.css -o public/swagger-ui/swagger-ui.css
          curl localhost:8080/swagger-ui/index.css -o public/swagger-ui/index.css
          curl localhost:8080/swagger-ui/favicon-32x32.png -o public/swagger-ui/favicon-32x32.png
          curl localhost:8080/swagger-ui/favicon-16x16.png -o public/swagger-ui/favicon-16x16.png
          curl localhost:8080/swagger-ui/swagger-ui-bundle.js -o public/swagger-ui/swagger-ui-bundle.js
          curl localhost:8080/swagger-ui/swagger-ui-standalone-preset.js -o public/swagger-ui/swagger-ui-standalone-preset.js
          curl localhost:8080/swagger-ui/swagger-initializer.js -o public/swagger-ui/swagger-initializer.js
      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
